### ISSUE TITLE
[译]如何隐藏DOM元素？

### ISSUE THREAD

**Issue by FrankKai** [FrankKai/FrankKai.github.io#142]
原文链接：https://allyjs.io/tutorials/hiding-elements.html

**Comment by FrankKai** [comment]
# 隐藏 DOM 元素
这篇文章的主要解释了多种隐藏DOM元素的实现方式。

当我们谈到一个元素被**隐藏**（hidden）时，我们通常是理解成**不可见**（not visible）。
然而，显示器不是唯一的应用隐藏内容的地方。电子阅读器和盲文显示器等系统依赖于accessibility树中的文档实现。

为了消除歧义，我们将进行以下的术语约定：

- **完全隐藏**（Completely hidden）
元素在屏幕上未渲染，在无障碍（accessibility）树中也不暴露，通过键盘获取不到访问权限。

- **语义上的隐藏**（Semantically hidden）
元素在屏幕上渲染，在无障碍树中不暴露，通过键盘可以获取到访问权限。

- **视觉上的隐藏**（Visually hidden）
元素在屏幕上未渲染，在无障碍树上暴露，通过键盘获取到访问权限。

通过以下表格可以很明确的对比出三种隐藏方式的异同：


visibility state | on screen | in accessibility tree | keyboard navigation
-- | -- | -- | --
completely hidden | hidden | hidden | not navigatable
semantically hidden | visible | hidden | navigatable
visually hidden | hidden | visible | navigatable

**Comment by FrankKai** [comment]
## 如何完全隐藏元素
完全隐藏一个元素有以下3种方式：
- 通过CSS属性display，例如：`display: none;`
- 通过CSS属性visibility，例如：`visibility: hidden;`
- 通过HTML5属性hidden，例如：`<span hidden>`

以上3种方式都会有相同的效果，内容不会被渲染也不会暴露在无障碍树中，他们有不同的表现效果。

###

**Comment by FrankKai** [comment]
## 如何语义上隐藏元素
为了将内容从无障碍树上隐藏，但是在屏幕上保留，我们可以使用属性`aria-hidden="true"`。

**Comment by FrankKai** [comment]
## 如何从视觉层面隐藏元素

为了确保使无障碍树的当前结构生效，我们也许需要提供不可见的内容。下面的CSS来自[HTML-bp](https://github.com/h5bp/html5-boilerplate/blob/v5.0.0/src/css/main.css#L126-L156)，这是基于无障碍隐藏元素的。
```css
.visuallyhidden {
  position: absolute;

  width: 1px;
  height: 1px;
  margin: -1px;
  border: 0;
  padding: 0;

  clip: rect(0 0 0 0);
  overflow: hidden;
}
```
CSS属性clip在任何浏览器都是被支持的，但是在CSS Masking 1中被弃用。取而代之的，我们建议使用`clip-path`，它还没有被广泛支持。所以会用`clip-path:inset(100%)`去覆盖`clip:rect(0 0 0 0)`样式。

当Internet Explorer 9 - 11使溢出的容器focusable，clip确保绘制的outline，:focus不可见，并且无法单击该元素。

说到可聚焦元素，我们可能会使用.visuallyhidden样式进行跳过链接，在这种情况下，我们需要一种方法来撤消视觉隐藏。 HTML5 Boilerplate为此提供了以下样式：
```css
.visuallyhidden.focusable:active,
.visuallyhidden.focusable:focus {
  position: static;

  width: auto;
  height: auto;
  margin: 0;

  clip: auto;
  overflow: visible;
}
```
但是，这种方法会带来一些问题。首先，我们需要通过添加可聚类类来声明元素兼容。第二，更重要的是 ，我们将样式重置为可能不是我们想要渲染的值。相反，我们可以使用：not()，这在每个现代浏览器中都受支持。 根据Beware推出的屏幕外可访问文本，上面的CSS片段可能会给某些屏幕阅读器带来问题。似乎（在某些情况下）单独的单词可能会被连接起来，因此很奇怪。幸运的是，我们可以通过添加white-space: nowrap来阻止空白的不希望的崩溃;。

### 2017版的.visuallyhidden
```
.visuallyhidden:not(:focus):not(:active) {
  position: absolute;

  width: 1px;
  height: 1px;
  margin: -1px;
  border: 0;
  padding: 0;

  white-space: nowrap;

  clip-path: inset(100%);
  clip: rect(0 0 0 0);
  overflow: hidden;
}
```
- 浏览器支持性好，兼容IE9-11。
- 它侧重于为可聚焦元素（如跳过链接）重新设置所有内容。
- 它是已经弃用的clip属性的替代。
